# Generated by Django 5.1.7 on 2025-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevists',
            name='page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
